
CREATE TABLE [HIKE].[Hiker](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[TrailName] [nvarchar](100) NOT NULL,
	[DateOfBirth] [date] NOT NULL,
	[Experience] [int] NOT NULL,
 CONSTRAINT [PK_Hiker] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

