
CREATE TABLE [HIKE].[Mountain](
	[Id] [bigint] IDENTITY(1,1)  NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Elevation] [bigint] NOT NULL,
	[Distance] [float] NOT NULL,
	[ElevationGain] [bigint] NOT NULL,
 CONSTRAINT [PK_Mountain] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

