CREATE TABLE [HIKE].[Trip](
	[Id] [bigint] IDENTITY(1,1)  NOT NULL,
	[HikerId] [bigint] NOT NULL,
	[MountainId] [bigint] NOT NULL,
	[TripDate] [date] NOT NULL,
	[Conditions] [bigint] NOT NULL,
	[Report] [nvarchar](max) NULL,
 CONSTRAINT [PK_Trip] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

