//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikingModelEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HikerDbEntities : DbContext
    {
        public HikerDbEntities()
            : base("name=HikerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Challenge> Challenge { get; set; }
        public virtual DbSet<Hiker> Hiker { get; set; }
        public virtual DbSet<Mountain> Mountain { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
    }
}
