//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HikingModelEF.Dto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HikerDto
    {
      
    
        // Declare constructor in the custom partial class file
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string TrailName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Experience { get; set; }
    }
}
